<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <PlatformTarget>x64</PlatformTarget>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <AssemblyName>ShinkouUI.Studio.Wpf</AssemblyName>
    <RootNamespace>ShinkouUI.Studio.Wpf</RootNamespace>
  </PropertyGroup>
  <Target Name="CopyShinkouRenderNative" AfterTargets="Build">
    <PropertyGroup>
      <NativeRenderDll>$(MSBuildProjectDirectory)\..\..\out\build\shinkou-render\shinkou_render_native.dll</NativeRenderDll>
    </PropertyGroup>
    <Copy SourceFiles="$(NativeRenderDll)" DestinationFolder="$(TargetDir)" SkipUnchangedFiles="true" Condition="Exists('$(NativeRenderDll)')" />
  </Target>
  <Target Name="CopyShinkouUiNative" AfterTargets="Build">
    <PropertyGroup>
      <NativeUiDll>$(MSBuildProjectDirectory)\..\..\out\build\shinkou-ui\shinkou_ui_native.dll</NativeUiDll>
    </PropertyGroup>
    <Copy SourceFiles="$(NativeUiDll)" DestinationFolder="$(TargetDir)" SkipUnchangedFiles="true" Condition="Exists('$(NativeUiDll)')" />
  </Target>
</Project>
